POST http://localhost:3001/register/id=xwIGdqA
Content-Type: application/json

{
  "__email":"furkanoral@hotmail.com",
  "__name":"Furkan",
  "__surname":"Oral",
  "__password":"123",
  "__permission": 
  {
    "__results": {
      "__request": {
        "__customerName": "Furkan",
        "__customerSurname": "Oral",
        "__bussinessName": "Yazılım Şirketi",
        "__requestId": "cmpR971",
        "__state": 1
    },
    "__success": true
  },
  "__acountManagerId": {
    "__value": "HHMaH1m3GPalrhR"
  },
  "__bussinessId": {
    "__value": "jo8ZfsKbEfF98a1"
  }
  }
}