POST http://localhost:3001/permission
Content-Type: application/json
{
    "packageType" : "TRIAL",
    "amount" : 15,
    "customerName" : "Furkan",
    "customerSurname" : "Oral",
    "bussinessName" : "Yazılım Şirketi"
}